module.exports = {
    version: '1.0.0',
    name: '',
    url: '',
    link: '',
    base: '',
    title: '',
    content: '',
    remove: '',
    retry: 10,
    wait: 0,
    encoding: 'utf-8',
    credit: true,
    headers: {},
    list: [],
    optiMode: 'quant',
    colors: 8,
    timeout: 8,
}